var mongoose = require("mongoose");

var rewardSchema = mongoose.Schema({
    round: String,
    name: String,
    email: String,
    totalarchive: Number,
    gen: Number,
    percentgen: Number,
    brex: Number,
    pointbrex: Number,
    percentbrex: Number,
    hk: Number,
    pointhk: Number,
    percenthk: Number,
    syr: Number,
    pointsyr: Number,
    percentsyr: Number,
    oth: Number,
    pointoth: Number, 
    percentoth: Number,
    grosstotal: Number,
    nettotal: Number,
    white: Number,
    acceptable: Number,
    unacceptable: Number,
    black: Number,
    penalty: Number,
    myvoid: Number,
    grosstotal: Number,
    nettotal: Number,
    overallpercent: Number,
    rewards: Number,
    uniquedom: Number,
    referrer: String,
    referral: Number,
    prize: Number,
    pot: Number,
    totalamount: Number,
    arweaverate: Number,
    arweavetotal: Number,
    remarks: String,
});

module.exports = mongoose.model("Reward", rewardSchema);
